version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    restart: always

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./admin:/app
      - ./logs:/app/logs
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '8000:8000'

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - admin
    env_file:
      - ./.env
    volumes:
      - ./bot:/app
      - ./logs:/app/logs
      - media_volume:/media
    command: python main.py

volumes:
  postgres_data:
  static_volume:
  media_volume:
