# Generated by Django 5.1.6 on 2025-03-05 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-parent_id', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
