# Generated by Django 5.1.6 on 2025-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [models.OrderBy(models.F('parent'), nulls_first=True), 'parent__name', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
