# Generated by Django 5.1.6 on 2025-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../media/products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
